version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: InsurancePortal.API/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=InsurancePortalDb;User=sa;Password=YourStrong!Passw0rd;
      - Redis__Configuration=redis:6379

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"

  redis:
    image: redis:7
    ports:
      - "6379:6379"